### PR TITLE
Update BAM Maestro to latest

### PR DESCRIPTION
**Pull request by tomoakley**
## Proposed Changes
Hi, we're using @perf-profiler/aws-maestro at TotallyMoney to run Maestro on AWS. However it's missing a few features from the latest releases, namely the `onFlowComplete` and `onFlowStart` hooks from 1.30.0. This PR updates your fork of Maestro to the latest version. I assume this is the package the @perf-profiler/aws-maestro package uses to run Maestro.

The only change I had to make was in maestro-cli/build.gradle had been replaced by maestro-cli/build.gradle.kts. I copied over the change in build.gradle to the new file.

## Testing
Unsure how to test, please advise.

### CODE REVIEW

**Comment by tomoakley** [comment]
@Almouro sorry to tag you - is there any chance we could get this merged? happy to test, although not exactly sure how

also realised that your commits to fix Maestro on AWS will be pushed down the commit history here. I hope that's ok.

**Comment by Almouro** [comment]
Hi @tomoakley, thanks for pinging, I'd missed the original PR notification

Thanks for the update! To test you should be able to generate a `maestro` executable with 
```bash
./gradlew distZip && unzip -o maestro-cli/build/distributions/maestro.zip -d dist
```
then try it out with `dist/maestro/bin/maestro test test.yaml` for instance

(see https://github.com/bamlab/maestro/tree/bam#release)

Let me know if that works!

**Comment by tomoakley** [comment]
Hi @Almouro - just built and tested on my M1 Pro MacBook using real device and emulator, both work fine. Is it also necessary to test on AWS? I had to make one change to the maestro-cli/build.gradle.kts (got the syntax slightly wrong).

**Comment by tomoakley** [comment]
hi @Almouro any update on this? thanks :)

**Comment by Almouro** [comment]
Hi @tomoakley, thanks for testing it out!
Merged and published, seems to work fine for us! 🥳

**Pull request merged**
